import time, math
from dataclasses import dataclass, field
from typing import Optional

@dataclass(slots=True)
class SymbolStats:
    """Symbol statistics with market data.
    OPTIMIZATION: Using __slots__ for 30-40% memory reduction (500-700 instances in memory).
    """
    symbol: str
    vol_quote: float = 0.0
    pct_change_24h: float = 0.0
    pct_change_15m: float = 0.0
    open_interest: float = 0.0
    oi_change_pct: float = 0.0  # Open interest change (stored for next cycle comparison)
    funding_rate: float = 0.0  # Current funding rate
    taker_buy_ratio: float = 0.5  # Taker buy vol / total taker vol
    long_short_ratio: float = 1.0  # Global long/short account ratio
    bid: float = 0.0
    ask: float = 0.0
    last: float = 0.0
    mark: float = 0.0
    spread_bps: float = 9999.0
    heat: float = 0.0
    last_seen: float = field(default_factory=time.time)
    contractSize: float = 1.0
    amount_step: float = 0.0
    price_tick: float = 0.0
    # Tracking fields for stale symbol detection
    last_scanned: float = 0.0  # When symbol was last scanned for signals
    signals_generated_count: int = 0  # Total signals generated by this symbol
    last_signal_time: float = 0.0  # When symbol last generated a signal

class DynamicUniverse:
    def __init__(self):
        self.stats = {}
        self.active = []
        self.btc_trend: Optional[float] = None  # BTC trend for correlation scoring
        self.last_rotation_time: float = 0.0  # Track when rotation last occurred
    
    def set_btc_trend(self, btc_trend: float):
        """Set BTC trend for correlation scoring."""
        self.btc_trend = btc_trend
    
    def score(self, st: SymbolStats) -> float:
        """
        Enhanced scoring system for better target selection.
        
        Factors considered:
        1. Volume (liquidity) - 30% weight
        2. Spread (execution cost) - 25% weight
        3. Momentum (24h price change) - 25% weight
        4. Signal quality potential - 15% weight
        5. BTC correlation - 5% weight (bonus)
        
        Returns:
            Score (higher is better, typically 0-10 range)
        """
        # 1. Volume component (30% weight) - logarithmic scale
        # Higher volume = better liquidity = higher score
        vol_log = math.log10(st.vol_quote + 1.0)
        vol_score = min(vol_log / 8.0, 1.0) * 3.0  # Normalize to 0-3.0
        
        # 2. Spread component (25% weight) - inverted (lower spread = higher score)
        # Tight spreads (< 30 bps) = high score, wide spreads (> 50 bps) = low score
        if st.spread_bps <= 30:
            spread_score = 2.5  # Maximum score for tight spreads
        elif st.spread_bps <= 40:
            spread_score = 2.0  # Good score
        elif st.spread_bps <= 50:
            spread_score = 1.0  # Moderate score
        else:
            spread_score = max(0.0, 1.0 - (st.spread_bps - 50) / 50.0)  # Penalty for wide spreads
        
        # 3. Momentum component (25% weight) - absolute price change
        # Strong momentum (> 2%) = high score, weak momentum (< 0.5%) = low score
        momentum_abs = abs(st.pct_change_24h)
        if momentum_abs >= 2.0:
            momentum_score = 2.5  # Strong momentum
        elif momentum_abs >= 1.0:
            momentum_score = 1.5 + (momentum_abs - 1.0)  # 1.5-2.5 range
        elif momentum_abs >= 0.5:
            momentum_score = 0.5 + (momentum_abs - 0.5) * 2.0  # 0.5-1.5 range
        else:
            momentum_score = momentum_abs * 1.0  # 0-0.5 range
        momentum_score = min(momentum_score, 2.5)  # Cap at 2.5
        
        # 4. Signal quality potential (15% weight)
        # Combines momentum strength and volume quality
        # Strong momentum + good volume = high signal potential
        momentum_strength = min(momentum_abs / 5.0, 1.0)  # Normalize to 0-1
        volume_quality = min(vol_log / 7.0, 1.0)  # Normalize to 0-1
        signal_potential = (momentum_strength * 0.6 + volume_quality * 0.4) * 1.5
        
        # 5. BTC correlation bonus (5% weight)
        # Reward symbols that move with BTC trend (for trend following)
        btc_bonus = 0.0
        if self.btc_trend is not None and abs(self.btc_trend) > 0.5:
            # Check if symbol moves in same direction as BTC
            if (st.pct_change_24h > 0 and self.btc_trend > 0) or \
               (st.pct_change_24h < 0 and self.btc_trend < 0):
                # Same direction = bonus
                correlation_strength = min(abs(st.pct_change_24h) / 3.0, 1.0)
                btc_bonus = correlation_strength * 0.5
        
        # Combine all components
        total_score = vol_score + spread_score + momentum_score + signal_potential + btc_bonus
        
        # Ensure non-negative
        return max(0.0, total_score)
    def _is_stale_symbol(self, st: SymbolStats, stale_threshold_seconds: float, cached_now: float = None) -> bool:
        """
        Check if symbol is stale (hasn't generated signals recently).
        OPTIMIZED: Accepts cached time to avoid repeated time.time() calls.
        
        Args:
            st: SymbolStats to check
            stale_threshold_seconds: Time threshold in seconds
            cached_now: Cached current time (optional)
        
        Returns:
            True if symbol is stale, False otherwise
        """
        # OPTIMIZATION: Use cached time if provided
        now = cached_now if cached_now is not None else time.time()
        # Consider stale if no signal generated in threshold time
        if st.last_signal_time > 0:
            time_since_signal = now - st.last_signal_time
            if time_since_signal > stale_threshold_seconds:
                return True
        # Also consider stale if never generated a signal and hasn't been scanned recently
        if st.signals_generated_count == 0 and st.last_scanned > 0:
            time_since_scan = now - st.last_scanned
            if time_since_scan > stale_threshold_seconds:
                return True
        return False
    
    def rotate(self, force_full_rotation: bool = False):
        """
        Rotate active symbol list, replacing stale symbols with fresh candidates.
        OPTIMIZED: Caches time and uses more efficient data structures.
        
        Args:
            force_full_rotation: If True, do full rotation. If False, only rotate stale symbols.
        """
        from .config import MAX_ACTIVE_SYMBOLS, STALE_SYMBOL_THRESHOLD_SEC, STALE_ROTATION_PCT
        
        # OPTIMIZATION: Cache time once per rotation
        now = time.time()
        
        # Basic quality filter
        quality_filter = lambda st: st.vol_quote > 2e6 and st.spread_bps < 60
        
        if force_full_rotation:
            # OPTIMIZATION: Pre-filter candidates before scoring
            candidates = []
            for s, st in self.stats.items():
                passed = quality_filter(st)
                if passed:
                    candidates.append((s, st))
            
            # Full rotation: rank all symbols and take top N
            ranked = sorted(
                [(s, self.score(st)) for s, st in candidates],
                key=lambda x: x[1],
                reverse=True
            )
            self.active = [s for s, _ in ranked[:MAX_ACTIVE_SYMBOLS]]
        else:
            # Smart rotation: replace stale symbols with fresh candidates
            # OPTIMIZATION: Use list comprehension for stale detection
            active_set = set(self.active)  # OPTIMIZATION: Convert to set for O(1) lookup
            stale_symbols = [
                symbol for symbol in self.active
                if (st := self.stats.get(symbol)) and 
                   self._is_stale_symbol(st, STALE_SYMBOL_THRESHOLD_SEC, cached_now=now)
            ]
            
            # Calculate how many to rotate (percentage of active list)
            num_to_rotate = max(1, int(len(self.active) * STALE_ROTATION_PCT))
            num_to_rotate = min(num_to_rotate, len(stale_symbols))  # Don't rotate more than available stale
            
            if num_to_rotate > 0:
                # OPTIMIZATION: Get fresh candidates (not in active list, meet quality threshold)
                # Pre-filter before scoring to reduce work
                # OPTIMIZATION: Store (symbol, score, stats) tuple to avoid redundant lookup
                fresh_candidates = [
                    (s, self.score(st), st) for s, st in self.stats.items()
                    if s not in active_set and quality_filter(st)
                ]
                
                # Score fresh candidates with freshness bonus
                # Symbols not scanned recently get bonus (they might have new momentum)
                # OPTIMIZATION: Use cached time and cache last_scanned lookups
                # OPTIMIZATION: st is already available from the tuple, no redundant lookup needed
                for i, (symbol, base_score, st) in enumerate(fresh_candidates):
                    if st:
                        # OPTIMIZATION: Cache last_scanned lookup
                        last_scanned = st.last_scanned
                        time_since_scan = now - last_scanned
                        
                        # Freshness bonus: reward symbols not recently scanned
                        # Never scanned gets highest bonus
                        if last_scanned == 0:  # Never scanned - highest priority
                            freshness_bonus = 1.0  # Highest bonus for never-scanned symbols
                        elif time_since_scan > 300:  # Not scanned in 5+ min
                            freshness_bonus = 0.5
                        elif time_since_scan > 120:  # Not scanned in 2+ min
                            freshness_bonus = 0.3
                        else:
                            freshness_bonus = 0.0
                        
                        # OPTIMIZATION: Cache pct_change_24h lookup
                        pct_change = st.pct_change_24h
                        # Recent momentum change bonus
                        momentum_bonus = 0.0
                        if abs(pct_change) > 1.5:  # Strong recent momentum
                            momentum_bonus = 0.3
                        
                        fresh_candidates[i] = (symbol, base_score + freshness_bonus + momentum_bonus)
                
                # Sort fresh candidates by score
                fresh_candidates.sort(key=lambda x: x[1], reverse=True)
                
                # Replace stale symbols with top fresh candidates
                for i, stale_symbol in enumerate(stale_symbols[:num_to_rotate]):
                    if i < len(fresh_candidates):
                        # Remove stale symbol
                        if stale_symbol in self.active:
                            self.active.remove(stale_symbol)
                        # Add fresh candidate
                        fresh_symbol = fresh_candidates[i][0]
                        self.active.append(fresh_symbol)
            
            # Ensure active list doesn't exceed max size
            if len(self.active) > MAX_ACTIVE_SYMBOLS:
                # Re-rank and keep top N
                ranked = sorted(
                    [(s, self.score(self.stats[s])) for s in self.active if s in self.stats],
                    key=lambda x: x[1],
                    reverse=True
                )
                self.active = [s for s, _ in ranked[:MAX_ACTIVE_SYMBOLS]]
        
        self.last_rotation_time = time.time()
    
    def get_discovery_candidates(
        self,
        max_candidates: int = 75,
        min_volume: float = 1e6,
        max_spread_bps: float = 80.0,
        min_momentum_pct: float = 1.0,
        stale_threshold_sec: float = 300.0
    ) -> list[str]:
        """
        Get discovery candidates: never-scanned, stale, or high-momentum symbols.
        
        Args:
            max_candidates: Maximum number of candidates to return
            min_volume: Minimum 24h volume for discovery (relaxed threshold)
            max_spread_bps: Maximum spread in bps for discovery (relaxed threshold)
            min_momentum_pct: Minimum momentum (absolute pct_change_24h) for discovery
            stale_threshold_sec: Time threshold for considering symbol stale
        
        Returns:
            List of symbol strings to scan for discovery
        """
        now = time.time()
        active_set = set(self.active)
        candidates = []
        
        # Relaxed quality filter for discovery
        discovery_filter = lambda st: st.vol_quote > min_volume and st.spread_bps < max_spread_bps
        
        for symbol, st in self.stats.items():
            # Skip if already in active list
            if symbol in active_set:
                continue
            
            # Must meet relaxed quality filter
            if not discovery_filter(st):
                continue
            
            # Priority 1: Never scanned (highest priority)
            if st.last_scanned == 0:
                candidates.append((symbol, 100.0, "never_scanned"))  # Highest score
                continue
            
            # Priority 2: Stale (not scanned recently) with strong momentum
            time_since_scan = now - st.last_scanned
            if time_since_scan > stale_threshold_sec:
                momentum_abs = abs(st.pct_change_24h)
                if momentum_abs >= min_momentum_pct:
                    # Score based on staleness and momentum
                    staleness_score = min(time_since_scan / 600.0, 1.0) * 50.0  # Up to 50 points for staleness
                    momentum_score = min(momentum_abs / 5.0, 1.0) * 30.0  # Up to 30 points for momentum
                    base_score = self.score(st)  # Base quality score
                    candidates.append((symbol, base_score + staleness_score + momentum_score, "stale_momentum"))
                    continue
            
            # Priority 3: Strong momentum even if recently scanned
            momentum_abs = abs(st.pct_change_24h)
            if momentum_abs >= min_momentum_pct * 1.5:  # Higher threshold for recently-scanned
                base_score = self.score(st)
                momentum_score = min(momentum_abs / 5.0, 1.0) * 20.0  # Up to 20 points
                candidates.append((symbol, base_score + momentum_score, "strong_momentum"))
        
        # Sort by score (descending) and return top candidates
        candidates.sort(key=lambda x: x[1], reverse=True)
        return [symbol for symbol, score, reason in candidates[:max_candidates]]
    
    def top_rows(self, n=8):
        rows = []
        for s in self.active[:n]:
            st = self.stats.get(s)
            if not st: continue
            rows.append(f"{s:<15} heat:{st.heat:4.1f} spr:{st.spread_bps:5.1f} vol:${st.vol_quote/1e6:5.2f}M")
        return rows
