# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'app',
        'app.bot',
        'app.config',
        'app.logger',
        'app.exchanges',
        'app.exchanges.binance_futures',
        'app.exchanges.factory',
        'app.position_manager',
        'app.signals',
        'app.order_manager',
        'app.exit_manager',
        'app.ui',
        'app.ui_rich',
        'app.universe',
        'app.indicators',
        'app.advanced_features',
        'app.feature_engine',
        'app.scoring',
        'app.scoring.engine',
        'app.scoring.modules',
        'app.scoring.adapter',
        'app.scoring.context',
        'app.scoring.model',
        'app.scoring.config',
        'app.ticker_cache',
        'app.fast_storage',
        'app.budget',
        'app.regime',
        'app.signal_scorer',
        'app.signal_confirmation',
        'app.validators',
        'app.llm_control',
        'ccxt.async_support',
        'ccxt.binanceusdm',
        'rich',
        'rich.console',
        'rich.layout',
        'rich.panel',
        'rich.table',
        'rich.text',
        'rich.live',
        'pandas',
        'numpy',
        'dotenv',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='UniRabbit',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

